### ISSUE TITLE
zsh: command not found: blacksmith

### ISSUE THREAD

**Issue by renege** [Indatus/blacksmith#1]
`zsh: command not found: blacksmith`

![notfound](https://dl.dropboxusercontent.com/s/toptem6p7h44mg0/fo.png?dl=1&token_hash=AAGb0mCnYJAtekc_kUgJXgpVEkFqRMllgaEKUhcJFLZfpw)

**Comment by brianwebb01** [comment]
Looks like you just moved blacksmith.phar to /usr/local/bin, you need to move & rename to 'blacksmith', then chmod so it is executable.
