### ISSUE TITLE
Generate different class in the same directory

### ISSUE THREAD

**Issue by ahmadshah** [Indatus/blacksmith#13]
Hi,

This is a sample from my template config file.

``` JSON
"controller": {
        "template": "controller.txt",
        "directory": "foo/bar/{{Entity}}/Controller",
        "filename": "{{Entity}}Controller.php"
    },
```

Based on the README, if i run `blacksmith generate Foo scaffold` it will create a new controller inside `foo/bar/User/Controller`. My question is it possible for me to create another controller eg `FoobarController.php` and the file will be inside `foo/bar/User/Controller` directory. Because if I'm not mistaken the command will be `blacksmith generate Foobar scaffold` so the **Entitiy** will now be Foobar instead of Foo.

**Comment by bkuhl** [comment]
You can create another config file and reference that in your original command.  So if you took `config.json` and made a `configUserController.json` you could change the path in that special file: 

``` json
"controller": {
        "template": "controller.txt",
        "directory": "foo/bar/User/Controller/{{Entity}}",
        "filename": "{{Entity}}Controller.php"
    },
```

Then you could use...

`blacksmith generate Foobar scaffold /path/to/configUserController.json`

**Comment by ahmadshah** [comment]
Ah okay that kinda solve my problem. Thanks.

Just wondering if the command can accept another argument such as `blacksmith generate Foobar scaffold /path/to/config.json --global="directory:User,foo:bar,bar:baz"` and we can use something like {{global.directory}} to retrieve the value. This can eliminate having multiple config files. 

What do you think?

**Comment by bkuhl** [comment]
There's a lot of value in simplicity.  Do you think this command line parameter is too complicated?  It seems like it'd be much simpler moving forward to resort to creating another config file, rather than trying to handle a lot of special scenarios via command line...

**Comment by ahmadshah** [comment]
For me the command line parameter is not that complicated. Just my scenario requires me to create another set of templates and not only just the config files. But it is still workable for me at the moment :smile:

**Comment by bkuhl** [comment]
Perhaps a more permanent feature should be to use `User.Foobar` as the entity to determine subdirectories and namespacing, whereas within templates only `Foobar` would be used as the Entity.  This would allow easy, simple commands with a lot of power.

**Comment by ahmadshah** [comment]
Thanks for the suggestion. Created a PR for that.
