### ISSUE TITLE
Is it possible to do a different config than hexagonal?

### ISSUE THREAD

**Issue by ahmadshah** [Indatus/blacksmith#15]
Am wondering how can I use a different type besides **hexagonal** and supplying different keys inside the config file.

``` json
"config_type": "foobar"
```

**Comment by brianwebb01** [comment]
That was the original intent, however presently there are no other config types.  Its more of a point for extension.  My initial thought was that there could be `hexagonal` and `mvc` or maybe `command_bus` and so on.

**Comment by ahmadshah** [comment]
Thanks for the clarification. Yup having the ability to specify our own template would be an awesome features. I'll try to tweak around with the source and see what I can help for this feature :smile:
