### ISSUE TITLE
Exception when self-updating

### ISSUE THREAD

**Issue by bkuhl** [Indatus/blacksmith#4]
Even though I have the latest version, I was curious about the self updating mechanism and hit a snag.  I see the following exception when updating.  It looks like the below URL actually redirects to `https://raw.githubusercontent.com/Indatus/blacksmith/master/blacksmith-manifest.json`.  Perhaps `file_get_contents()` doesn't like redirects?

```
$ blacksmith self-update
Looking for updates...

  [Herrera\Json\Exception\FileException]
  file_get_contents(https://github.com/Indatus/blacksmith/raw/master/blacksmith-manifest.json): failed to open stream: operation failed

self-update [-p|--pre] [-r|--redo] [-u|--upgrade]
```

**Comment by brianwebb01** [comment]
Weird, I wonder if github changed something recently?  I just ran this process yesterday on the newest code version and it worked without issue.

**Comment by bkuhl** [comment]
It must've been a Github issue.  It's working now!
