### ISSUE TITLE
InstanceInterface is not generated

### ISSUE THREAD

**Issue by bkuhl** [Indatus/blacksmith#6]
There doesn't seem to be an `Instances/InstanceInterface.php` generated in `Contracts` within lib using the json config packaged with Blacksmith.  Is this intentional or a bug?

**Comment by brianwebb01** [comment]
Intentional.  The InstanceInterface is part of the Laravel Hexagonal pattern, it doesn't change with each model.  I believe there are several interfaces that the templates use that fall into this same category.
